[meta]
name = "Catppuccin Mocha"
dark = true
author = "Catppuccin"

[ui]
background = "#1e1e2e"
gutter = "#181825"
foreground = "#cdd6f4"
line_number = "#585b70"
line_number_active = "#cdd6f4"
border = "#313244"
cursor = "#f5e0dcdc"
cursor_line = "#3132448c"
selection = "#45475ad2"
active_pane_border = "#89b4fa"
bracket_match = "#89b4fa46"
scrollbar_thumb = "#585b70b4"
statusbar_bg = "#181825"
statusbar_fg = "#a6e3a1"
statusbar_dim = "#89b4fa"
status_mode_bg = "#313244"
scrim = "#0000006e"
picker_bg = "#181825"
picker_border = "#45475a"
picker_input_bg = "#11111b"
picker_selection = "#313244"
picker_fg = "#cdd6f4"
picker_detail = "#7f849c"
picker_prompt = "#cba6f7"
search_match = "#f9e2af46"
search_match_active = "#fab38796"

[syntax]
default = "#cdd6f4"
keyword = "#cba6f7"
keyword_control = "#f38ba8"
type = "#89b4fa"
string = "#a6e3a1"
comment = "#585b70"
number = "#fab387"
macro = "#89dceb"
attribute = "#f5c2e7"
lifetime = "#f5c2e7"
function = "#89b4fa"
operator = "#89dceb"

[lsp]
error = "#f38ba8"
warning = "#f9e2af"
info = "#89b4fa"
hint = "#a6e3a1"

[terminal]
ansi = [
  "#45475a", "#f38ba8", "#a6e3a1", "#f9e2af",
  "#89b4fa", "#f5c2e7", "#94e2d5", "#bac2de",
  "#585b70", "#f38ba8", "#a6e3a1", "#f9e2af",
  "#89b4fa", "#f5c2e7", "#94e2d5", "#a6adc8",
]
